# Generated by Django 4.2.4 on 2023-08-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.CharField(
                choices=[("F", "Food"), ("S", "Starter"), ("B", "Beverage")],
                default="F",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="food",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
