# Generated by Django 4.2.4 on 2023-09-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foods", "0002_food_category_food_image_food_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
