# Generated by Django 4.2.4 on 2023-09-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doneorder",
            name="address",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="doneorder",
            name="final_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="final_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
