# Generated by Django 4.2.4 on 2023-09-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("loyalty_club", "0001_initial"),
        ("orders", "0002_alter_doneorder_address_alter_doneorder_final_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doneorder",
            name="coupon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="loyalty_club.coupon",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="loyalty_club.coupon",
            ),
        ),
    ]
