# Generated by Django 4.2.4 on 2023-09-13 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("duration", models.DurationField()),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("F", "Fixed price"), ("P", "Percentage")],
                        max_length=1,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "for_users",
                    models.CharField(
                        choices=[
                            ("AL", "All users"),
                            ("JE", "Join date Equal to y-m-d"),
                            ("JB", "Join date Before y-m-d"),
                            ("JA", "Join date After y-m-d"),
                            ("SE", "Score Equal to n"),
                            ("SL", "Score Less than n"),
                            ("SM", "Score More than n"),
                        ],
                        max_length=2,
                    ),
                ),
                ("score", models.IntegerField()),
                ("join_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="LoyaltyClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_date", models.DateField(default=django.utils.timezone.now)),
                ("score", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
