# Generated by Django 4.2.4 on 2023-09-13 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_uuid", models.UUIDField()),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "not paid"),
                            (1, "Paid but not verified"),
                            (2, "paid and verified"),
                        ],
                        default=0,
                    ),
                ),
                ("payment_id", models.CharField(max_length=128)),
                ("payment_link", models.URLField(max_length=512)),
                ("idpay_status", models.IntegerField(default=0)),
                ("idpay_track_id", models.IntegerField(default=0)),
                ("idpay_order_id", models.CharField(max_length=50)),
                ("idpay_card_no", models.CharField(max_length=20)),
                ("idpay_hashed_card_no", models.CharField(max_length=64)),
                ("idpay_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
